### PR TITLE
Add homework

### PR DESCRIPTION
**Pull request by panza87**
Difficulty... 2!

### CODE REVIEW

**Comment by Phoboes** [comment]
Awesome. It all looks pretty good, how are you feeling about things?

**Comment by panza87** [comment]
Sweet! Good to hear, feeling good about everything so far. Looking forward to getting into some of the harder stuff!

**Comment by Phoboes** [comment]
I've had a bit more time to sift through your code, as I said last time - everything looks really good, I do have a couple of small notes:

  - I would try and be a little less cryptic with your variable names. For the most part they are pretty good, 
    but things like `if (i === off)` will be really confusing coming back to the code down the line - well 
   named variables can save you a lot of time in the amount of commentary you need to write out, and 
   following the flow of the program easily. With that said, good job actually annotating your code. It will 
   save you a lot of headaches coming back to review old code etc.

  - Your MTA is very slightly bugged, they're tiny fixes, but I figured I'd throw them here for you to consider 
    next time: 
      + Your count is being thrown off by 1, I suspect it's union square being counted twice, as
         single station  travel returns a value of 1 instead of 2.
      + Starting a trip at Union square gets strange string concatenations from line 17.

```You must travel through the following stops on Subway 6: and Union Square.
Change at Union Square to Subway N.
Your journey continues through the following stops: Union Square, 23rd, 28th, 34th, and Times Square.
 There were a total of 6 stops.```

If you're curious, these are the tests I ran through:

``` javascript 
planTrip(sub6, '28th', subN, "8th")
console.warn( "Line 6: 28th, 23rd, /Union Square/, 8th on line N ")
planTrip(sub6, '28th', subL, "1st")
console.warn(" Line 6: 28 23 Union Square 3rd 1st on line L")
planTrip(sub6, '28th', sub6, "Astor Place")
console.warn(" Line 6: 28th, 23, /Union Square/, Astor Place on line 6 ")
planTrip(sub6, 'Astor Place', sub6, "28th")
console.warn(" Line 6: Astor Place, /Union Square/, 23, 28th on line ")
planTrip(sub6, '28th', subN, "34th")
console.warn(" Line 6: 28th 23rd /Union Square/ 23 28 34 ")
planTrip(sub6, "28th", sub6, "28th")
console.warn(" Line 6: 0 ")
planTrip(sub6, 'Union Square', subN, 'Times Square');
console.warn(" Line 6: Union square 23 28 34 Times Square ")
``` 

Overall, you've done a really good job - It's good to see that you seem to have had fun with it and went back to refine things to learn further.

**Comment by panza87** [comment]
That’s awesome, thanks for taking the time to look through! 

I’ll jump back to it and fix it up when i finish off my tic tac toe. Working on my AI at the moment! This is a lot harder then i thought it would be after starting to code the computer moves.. Gonna be a long week… And many many lines of code : /

**Pull request merged**
